include:
  - local: gitlab-ci/yaml-files/checkpatch_test/checkpatch-gitlab-ci.yml
  - local: gitlab-ci/yaml-files/mpu_build/g3s-gitlab-ci.yml
  - local: gitlab-ci/yaml-files/mpu_build/n2h-gitlab-ci.yml
  - local: gitlab-ci/yaml-files/mpu_build/t2h-gitlab-ci.yml
  - local: gitlab-ci/yaml-files/mpu_build/v2h-gitlab-ci.yml

stages:
  - build
  - test
