stages:
  - pre_test
  - tag_creation
  - static_analysis_testing
  - mpu_build_testing
  - klocwork

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "schedule"
      when: always

include:
  - local: gitlab-ci/merge-gateway-pipeline.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - local: gitlab-ci/dev-overnight-pipeline.yml
    rules:
      - if: $DEV_OVERNIGHT == "true" && ($CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web")
  - local: gitlab-ci/tag-overnight-pipeline.yml
    rules:
      - if: $TAG_OVERNIGHT == "true" && ($CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "web")

RZ MPU Git Automation:
  stage: pre_test
  script: echo "RZ MPU Git Automation starting..."
  interruptible: true
