#######################################################################################################################
# Copyright [2024] Renesas Electronics Corporation and/or its licensors. All Rights Reserved.
#
# The contents of this file (the "contents") are proprietary and confidential to Renesas Electronics Corporation
# and/or its licensors ("Renesas") and subject to statutory and contractual protections.
#
# Unless otherwise expressly agreed in writing between Renesas and you: 1) you may not use, copy, modify, distribute,
# display, or perform the contents; 2) you may not use any name or mark of Renesas for advertising or publicity
# purposes or in connection with your use of the contents; 3) RENESAS MAKES NO WARRANTY OR REPRESENTATIONS ABOUT THE
# SUITABILITY OF THE CONTENTS FOR ANY PURPOSE; THE CONTENTS ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
# NON-INFRINGEMENT; AND 4) RENESAS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES,
# INCLUDING DAMAGES RESULTING FROM LOSS OF USE, DATA, OR PROJECTS, WHETHER IN AN ACTION OF CONTRACT OR TORT, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE CONTENTS. Third-party contents included in this file may
# be subject to different terms.
#######################################################################################################################

#######################################################################################################################
# Description: Yaml file containing templates for MPU build tests.
#######################################################################################################################

########################################## checkpatch_test_job_template ###############################################
# 1. Contains basic template for checkpatch testing.
# 2. Error checks in place to see all checkpatch test files exist and the checkpatch script has executable
#    permissions.
# 3. Reference and target branches are both locally checked out to run the test locally.
# 4. The checkpatch script run line is ORed with true so the result can be analysed and pipeline output can be
#    determined manually later.
# 5. In case warnings are found in the log, the pipeline passes with allow_failure which gives a warning sign on the
#    pipeline. In case errors are found in the log, the pipeline fails.
#######################################################################################################################
.checkpatch_test_job_template: &checkpatch_test_job_template
  stage: static_analysis_testing
  variables:
    REFERENCE_BRANCH: ""
    TARGET_BRANCH: ""
  script:
    - echo "TARGET BRANCH - ${TARGET_BRANCH}"
    - echo "REFERENCE BRANCH - ${REFERENCE_BRANCH}"
    - CHECKPATCH_SCRIPT=../scripts/checkpatch/checkpatch.pl
    - SPELLING_FILE=../scripts/checkpatch/spelling.txt
    - CONST_STRUCTS_FILE=../scripts/checkpatch/const_structs.checkpatch
    - if [ ! -f $CHECKPATCH_SCRIPT ]; then
    - echo "checkpatch.pl does not exist, check if the file path is correct"
    - exit 1
    - elif [ ! -f $SPELLING_FILE ]; then
    - echo "spelling.txt file does not exist, check if the file path is correct"
    - exit 1
    - elif [ ! -f $CONST_STRUCTS_FILE ]; then
    - echo "const_structs.checkpatch file does not exist, check if the file path is correct"
    - exit 1
    - elif [[ ! -x "$CHECKPATCH_SCRIPT" ]]; then
    - echo "Checkpatch script is not executable, set permission to 'Allow executing file as program'"
    - exit 1
    - else
    - git fetch origin $REFERENCE_BRANCH
    - git checkout $REFERENCE_BRANCH
    - git fetch origin $TARGET_BRANCH
    - git checkout $TARGET_BRANCH
    - git diff --unified=5 $REFERENCE_BRANCH > test.patch
    - ($CHECKPATCH_SCRIPT test.patch --max-line-length=160 > checkpatch.log) || true
    - if grep -q "ERROR:" checkpatch.log; then
    - exit 1
    - elif grep -q "WARNING" checkpatch.log; then
    - exit 2
    - else
    - exit 0
    - fi
    - fi
  allow_failure:
    exit_codes: 2
  interruptible: true
  artifacts:
    expire_in: 1 week
    when: always
    name: "RZ Checkpatch files"
    paths:
      - ./test.patch
      - ./checkpatch.log

############################################ mpu_build_job_template ###################################################
# 1. Contains basic template for building MPU code.
# 2. All the variables listed are required in the mpu_build.sh script.
#######################################################################################################################
.mpu_build_job_template: &mpu_build_job_template
  stage: mpu_build_testing
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    TARGET_OS: ""
    CONFIGS: ""
    TEST_TYPE: ""
    ERROR_MSG: ""
  interruptible: true

########################################## linux_mpu_build_job_template ###############################################
# 1. Extends the basic template for a Linux environment.
# 2. Separate runner for every platform for every pipeline type.
# 3. For the main and tag pipeline, the control is in the workspace directory, hence moving to that directory 
#    before any command.
#######################################################################################################################
.linux_mpu_build_job_template: &linux_mpu_build_job_template
  <<: *mpu_build_job_template
  tags:
    - "${PLAT}_${PIPELINE_TYPE}_tests"
  before_script:
    - if $PIPELINE_TYPE == "main" || $PIPELINE_TYPE == "tag"
    - cd "../workspace/tf-a"
    - fi
    - export CROSS_COMPILE=../compiler/gcc-arm-8.3-2019.03-x86_64-aarch64-elf/bin/aarch64-elf-
    - make PLAT=$PLAT realclean BOARD=$BOARD
  script:
    - if $PIPELINE_TYPE == "tag"
    - ../../tf-a/scripts/mpu_build.sh $PLAT $BOARD $BUILD_TYPE "${TARGET_OS}" "${CONFIGS}" "${TEST_TYPE}" "${ERROR_MSG}"
    - else
    - scripts/mpu_build.sh $PLAT $BOARD $BUILD_TYPE "${TARGET_OS}" "${CONFIGS}" "${TEST_TYPE}" "${ERROR_MSG}"
    - fi

####################################### linux_mpu_build_success_job_template ##########################################
# 1. Extends the Linux template for a success test case.
# 2. For main an tag, after building the TF-A .bin and .srec files, the files are moved to the default runner 
#    tf-a directory. This is because job artifacts are only picked from the default runner tf-a directory.
# 3. The artifacts are set to expire in 1 week, as this would help manage storage space efficiently and 1 week is
#    sufficient time for the deletion to not impact any work or testing.
#######################################################################################################################
.linux_mpu_build_success_job_template:
  <<: *linux_mpu_build_job_template
  after_script:
    - if $PIPELINE_TYPE == "main" || $PIPELINE_TYPE == "tag"
    - mkdir -p build && cd build
    - mkdir -p $PLAT && cd $PLAT
    - cp -r "../../../workspace/tf-a/build/${PLAT}/${BUILD_TYPE}" .
    - fi
  artifacts:
    expire_in: 1 week
    when: always
    name: "$CI_JOB_NAME"
    paths:
      - ./build/$PLAT/$BUILD_TYPE/*.bin
      - ./build/$PLAT/$BUILD_TYPE/*.srec

####################################### linux_mpu_build_failure_job_template ##########################################
# 1. Extends the Linux template for a failure test case.
# 2. There are no additional requirements or procedures required after running the mpu_build.sh as it's all built
#    within the script.
#######################################################################################################################
.linux_mpu_build_failure_job_template:
  <<: *linux_mpu_build_job_template