#######################################################################################################################
# Copyright [2024] Renesas Electronics Corporation and/or its licensors. All Rights Reserved.
#
# The contents of this file (the "contents") are proprietary and confidential to Renesas Electronics Corporation
# and/or its licensors ("Renesas") and subject to statutory and contractual protections.
#
# Unless otherwise expressly agreed in writing between Renesas and you: 1) you may not use, copy, modify, distribute,
# display, or perform the contents; 2) you may not use any name or mark of Renesas for advertising or publicity
# purposes or in connection with your use of the contents; 3) RENESAS MAKES NO WARRANTY OR REPRESENTATIONS ABOUT THE
# SUITABILITY OF THE CONTENTS FOR ANY PURPOSE; THE CONTENTS ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
# NON-INFRINGEMENT; AND 4) RENESAS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES,
# INCLUDING DAMAGES RESULTING FROM LOSS OF USE, DATA, OR PROJECTS, WHETHER IN AN ACTION OF CONTRACT OR TORT, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE CONTENTS. Third-party contents included in this file may
# be subject to different terms.
#######################################################################################################################

#######################################################################################################################
# Description: Yaml file containing templates for main branch MPU build tests.
#######################################################################################################################

######################################### prep_for_main_build_job_template ############################################
# 1. Template for preparation job which runs before the build jobs for the main branch
# 2. It locally merges the integration branch into the main branch
#######################################################################################################################
.prep_for_main_build_job_template:
  stage: pre_test
  variables:
    PLAT: ""
  tags:
    - "${PLAT}_main_tests"
  script:
    - cd "../workspace"
    - rm -r -f ./*
    - git clone http://svc_sp3_ci_etcetc:DC_p5HnJoAsvmocwdYer@global-infra-jp-main.dgn.renesas.com/products/common/bootloader/soc/tf-a.git
    - cd tf-a
    - git checkout $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git checkout $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git merge $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - git status

########################################### main_build_job_template ###################################################
# 1. Contains basic template for building MPU code within main branch.
# 2. All the variables listed are required in the mpu_build.sh script.
#######################################################################################################################
.main_build_job_template: &main_build_job_template
  stage: mpu_build_testing
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    TARGET_OS: ""
    CONFIGS: ""
    TEST_TYPE: "main"
    ERROR_MSG: ""
  interruptible: true

########################################## linux_main_build_job_template ###############################################
# 1. Extends the basic template for a Linux environment.
# 2. Separate runner for every platform within the main branch.
#######################################################################################################################
.linux_main_build_job_template: &linux_main_build_job_template
  <<: *main_build_job_template
  tags:
    - "${PLAT}_main_tests"
  before_script:
    - cd "../workspace/tf-a"
    - git status
    - export CROSS_COMPILE=../../compiler/gcc-arm-8.3-2019.03-x86_64-aarch64-elf/bin/aarch64-elf-
    - make PLAT=$PLAT realclean BOARD=$BOARD
  script:
    - scripts/mpu_build.sh $PLAT $BOARD $BUILD_TYPE "${TARGET_OS}" "${CONFIGS}" "${TEST_TYPE}" "${ERROR_MSG}"

####################################### linux_main_build_success_job_template ##########################################
# 1. Extends the Linux template for a success test case.
# 2. The artifacts are set to expire in 1 week, as this would help manage storage space efficiently and 1 week is
#    sufficient time for the deletion to not impact any work or testing.
#######################################################################################################################
.linux_main_build_success_job_template:
  <<: *linux_main_build_job_template
  after_script:
    - mkdir -p build && cd build
    - mkdir -p $PLAT && cd $PLAT
    - cp -r "../../../workspace/tf-a/build/${PLAT}/${BUILD_TYPE}" .
  artifacts:
    expire_in: 1 week
    when: always
    name: "$CI_JOB_NAME"
    paths:
      - ./build/$PLAT/$BUILD_TYPE/*.bin
      - ./build/$PLAT/$BUILD_TYPE/*.srec

####################################### linux_main_build_failure_job_template ##########################################
# 1. Extends the Linux template for a failure test case.
# 2. There are no additional requirements or procedures required after running the mpu_build.sh as it's all built
#    within the script.
#######################################################################################################################
.linux_main_build_failure_job_template:
  <<: *linux_main_build_job_template
