#######################################################################################################################
# Copyright [2024] Renesas Electronics Corporation and/or its licensors. All Rights Reserved.
#
# The contents of this file (the "contents") are proprietary and confidential to Renesas Electronics Corporation
# and/or its licensors ("Renesas") and subject to statutory and contractual protections.
#
# Unless otherwise expressly agreed in writing between Renesas and you: 1) you may not use, copy, modify, distribute,
# display, or perform the contents; 2) you may not use any name or mark of Renesas for advertising or publicity
# purposes or in connection with your use of the contents; 3) RENESAS MAKES NO WARRANTY OR REPRESENTATIONS ABOUT THE
# SUITABILITY OF THE CONTENTS FOR ANY PURPOSE; THE CONTENTS ARE PROVIDED "AS IS" WITHOUT ANY EXPRESS OR IMPLIED
# WARRANTY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
# NON-INFRINGEMENT; AND 4) RENESAS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, OR CONSEQUENTIAL DAMAGES,
# INCLUDING DAMAGES RESULTING FROM LOSS OF USE, DATA, OR PROJECTS, WHETHER IN AN ACTION OF CONTRACT OR TORT, ARISING
# OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE CONTENTS. Third-party contents included in this file may
# be subject to different terms.
#######################################################################################################################

#######################################################################################################################
# Description: Yaml file containing N2H main merge gateway MPU build jobs.
#######################################################################################################################

################################################## include ############################################################
include:
  - local: gitlab-ci/templates/main-mpu-build-templates.yml

<<<<<<<< HEAD:gitlab-ci/main_mpu_build/n2h-gitlab-ci.yml
################################### Preparation job for main branch N2H build jobs ####################################
rzn2h-prep-for-main-build-job:
  variables:
    PLAT: "n2h"
  extends:
    - .prep_for_main_build_job_template

######################################## N2H eval MPU build jobs : main branch ########################################
========
######################################## N2H eval MPU build jobs : tag ################################################
>>>>>>>> 1db9ccda3 (Porting Git Automation v4.3: Main branch Merge Gateway):gitlab-ci/tag_mpu_build/n2h-gitlab-ci.yml
rzn2h-release-core4:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=4"
  extends:
    - .linux_main_build_success_job_template

rzn2h-release-core2:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=2"
  extends:
    - .linux_main_build_success_job_template

rzn2h-release-core1:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=1"
  extends:
    - .linux_main_build_success_job_template

rzn2h-release-core0:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=0"
    ERROR_MSG: "PLATFORM_CORE_COUNT is set to illegal value. It should either be set for 1,2 or 4 CA55 cores"
  extends:
    - .linux_main_build_failure_job_template

rzn2h-release-core5:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=5"
    ERROR_MSG: "PLATFORM_CORE_COUNT is set to illegal value. It should either be set for 1,2 or 4 CA55 cores"
  extends:
    - .linux_main_build_failure_job_template

rzn2h-release-stack-protector-0:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    CONFIGS: "ENABLE_STACK_PROTECTOR=0"
    ERROR_MSG: "unrecognized command line option '-fstack-protector-0'; did you mean '-fstack-protector'?"
  extends:
    - .linux_main_build_failure_job_template

rzn2h-debug-log0:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=0 PLATFORM_CORE_COUNT=4"
  extends:
    - .linux_main_build_success_job_template

rzn2h-debug-log50:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=4"
  extends:
    - .linux_main_build_success_job_template

rzn2h-debug-log50-core2:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=2"
  extends:
    - .linux_main_build_success_job_template

rzn2h-debug-log50-core1:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=1"
  extends:
    - .linux_main_build_success_job_template

rzn2h-debug-log50-core0:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=0"
    ERROR_MSG: "PLATFORM_CORE_COUNT is set to illegal value. It should either be set for 1,2 or 4 CA55 cores"
  extends:
    - .linux_main_build_failure_job_template

rzn2h-debug-log50-core5:
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=5"
    ERROR_MSG: "PLATFORM_CORE_COUNT is set to illegal value. It should either be set for 1,2 or 4 CA55 cores"
  extends:
    - .linux_main_build_failure_job_template
