/*
 * Copyright (c) 2020, Renesas Electronics Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <arch.h>
#include <asm_macros.S>
#include <console_macros.S>

	.globl	console_rzg2l_register
	.globl	console_rzg2l_init
	.globl	console_rzg2l_putc
	.globl	console_rzg2l_flush

func console_rzg2l_register
endfunc console_rzg2l_register

func console_rzg2l_init
endfunc console_rzg2l_init

func console_rzg2l_putc
endfunc console_rzg2l_putc

func console_rzg2l_flush
endfunc console_rzg2l_flush
