include:
  - local: gitlab-ci/templates/dev-mpu-build-templates.yml

rzt2h-release-core4:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=4"
  extends:
    - .linux_mpu_build_success_job_template

rzt2h-release-core2:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=2"
  extends:
    - .linux_mpu_build_success_job_template

rzt2h-release-core1:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=1"
  extends:
    - .linux_mpu_build_success_job_template

rzt2h-release-core0:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=0"
  extends:
    - .linux_mpu_build_failure_job_template

rzt2h-release-core5:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "release"
    CONFIGS: "PLATFORM_CORE_COUNT=5"
  extends:
    - .linux_mpu_build_failure_job_template

rzt2h-release-stack-protector-0:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "release"
    CONFIGS: "ENABLE_STACK_PROTECTOR=0"
  extends:
    - .linux_mpu_build_failure_job_template

rzt2h-debug-log0:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=0 PLATFORM_CORE_COUNT=4"
  extends:
    - .linux_mpu_build_success_job_template

rzt2h-debug-log50:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=4"
  extends:
    - .linux_mpu_build_success_job_template

rzt2h-debug-log50-core2:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=2"
  extends:
    - .linux_mpu_build_success_job_template

rzt2h-debug-log50-core1:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=1"
  extends:
    - .linux_mpu_build_success_job_template

rzt2h-debug-log50-core0:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=0"
  extends:
    - .linux_mpu_build_failure_job_template

rzt2h-debug-log50-core5:
  variables:
    PLAT: "t2h"
    BOARD: "dev_1"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLATFORM_CORE_COUNT=5"
  extends:
    - .linux_mpu_build_failure_job_template
