##########################################################
#..............MPU BUILD JOB TEMPLATES...................#
##########################################################
.mpu_build_job_template: &mpu_build_job_template
  stage: mpu_build_testing
  variables:
    PLAT: "n2h"
    BOARD: "eval"
    BUILD_TYPE: "release"
    CONFIGS: ""
  interruptible: true

.linux_mpu_build_job_template: &linux_mpu_build_job_template
  <<: *mpu_build_job_template
  tags:
    - "${PLAT}_tests"
  before_script:
    - export CROSS_COMPILE=../compiler/gcc-arm-8.3-2019.03-x86_64-aarch64-elf/bin/aarch64-elf-
    - make PLAT=$PLAT realclean BOARD=$BOARD
  artifacts:
    expire_in: 1 week
    when: always
    name: "$CI_JOB_NAME"
    paths:
      - ./build/$PLAT/$BUILD_TYPE/*.bin
      - ./build/$PLAT/$BUILD_TYPE/*.srec

.linux_mpu_build_success_job_template:
  <<: *linux_mpu_build_job_template
  script:
    - gitlab-ci/scripts/mpu_build/mpu_build.sh $PLAT $BOARD $BUILD_TYPE "${CONFIGS}"

.linux_mpu_build_failure_job_template:
  <<: *linux_mpu_build_job_template
  script:
    - ( ! gitlab-ci/scripts/mpu_build/mpu_build.sh $PLAT $BOARD $BUILD_TYPE "${CONFIGS}" )