include:
  - local: gitlab-ci/templates/tag-mpu-build-templates.yml

rzg3e-release-dev-1:
  variables:
    PLAT: "g3e"
    BOARD: "dev_1"
    BUILD_TYPE: "release"
    CONFIGS: ""
  extends:
    - .linux_tag_build_success_job_template

rzg3e-release-dev-1-stack-protector-0:
  variables:
    PLAT: "g3e"
    BOARD: "dev_1"
    BUILD_TYPE: "release"
    CONFIGS: "ENABLE_STACK_PROTECTOR=0"
  extends:
    - .linux_tag_build_failure_job_template

rzg3e-debug-log0-dev-1:
  variables:
    PLAT: "g3e"
    BOARD: "dev_1"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=0"
  extends:
    - .linux_tag_build_success_job_template

rzg3e-debug-log50-dev-1:
  variables:
    PLAT: "g3e"
    BOARD: "dev_1"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50"
  extends:
    - .linux_tag_build_success_job_template
