/*
 * Copyright (c) 2023, Renesas Electronics Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _XSPI_REG_H_
#define _XSPI_REG_H_


#define XSPI_WRAPCFG_OFFSET			UL(0x000)
#define XSPI_COMCFG_OFFSET			UL(0x004)
#define XSPI_BMCFG_OFFSET			UL(0x008)
#define XSPI_CMCFG0CS0_OFFSET		UL(0x010)
#define XSPI_CMCFG1CS0_OFFSET		UL(0x014)
#define XSPI_CMCFG2CS0_OFFSET		UL(0x018)
#define XSPI_LIOCFGCS0_OFFSET		UL(0x050)
#define XSPI_BMCTL0_OFFSET			UL(0x060)
#define XSPI_CSSCTL_OFFSET			UL(0x06C)
#define XSPI_CDCTL0_OFFSET			UL(0x070)
#define XSPI_CDTBUF0_OFFSET			UL(0x080)
#define XSPI_CDABUF0_OFFSET			UL(0x084)
#define XSPI_CDD0BUF0_OFFSET		UL(0x088)
#define XSPI_LIOCTL_OFFSET			UL(0x108)
#define XSPI_INTS_OFFSET			UL(0x190)
#define XSPI_INTC_OFFSET			UL(0x194)

#define XSPI_CDTBUF_CMDSIZE_OFFSET	(0U)
#define XSPI_CDTBUF_CMDSIZE_MSK		(0x3U << XSPI_CDTBUF_CMDSIZE_OFFSET)
#define XSPI_CDTBUF_ADDSIZE_OFFSET	(2U)
#define XSPI_CDTBUF_ADDSIZE_MSK		(0x7U << XSPI_CDTBUF_ADDSIZE_OFFSET)
#define XSPI_CDTBUF_DATASIZE_OFFSET	(5U)
#define XSPI_CDTBUF_LATE_OFFSET		(9U)
#define XSPI_CDTBUF_TRTYPE_OFFSET	(15U)
#define XSPI_CDTBUF_CMD_OFFSET		(16U)

#define XSPI_INTC_CMDCMPC			(0U)
#define XSPI_INTC_CMDCMPC_MSK		(0x1U << XSPI_INTC_CMDCMPC)

#define XSPI_INTS_CMDCMP			(0U)
#define XSPI_INTS_CMDCMP_MSK		(0x1U << XSPI_INTS_CMDCMP)

#define XSPI_CDCTL0_TRREQ			(0U)
#define XSPI_CDCTL0_TRREQ_MSK		(0x1U << XSPI_CDCTL0_TRREQ)

#define XSPI_BMCTL0_CH0CS0ACC_READ	(0x1)
#define XSPI_BMCTL0_CH0CS0ACC_WRITE	(0x2)

/* LIOCFGCSn Register */
#define XSPI_LIOCFGCS_PRTMD			U(0)
#define XSPI_LIOCFGCS_PRTMD_1S_1S_1S	UL(0x0000)
#define XSPI_LIOCFGCS_PRTMD_8D_8D_8D	UL(0x03FF)
#define XSPI_LIOCFGCS_LATEMD		U(10)

/* CMCFG0CSN Register */
#define XSPI_CMCFG0CS_FFMT			U(0)
#define XSPI_CMCFG0CS_ADDSIZE		UL(2)

/* CMCFG1CSn Register */
#define XSPI_CMCFG1CS_RDCMD			UL(0)
#define XSPI_CMCFG1CS_RDLATE		UL(16)

/* BMCTL0 Register */
#define XSPI_BMCTL0_CS0ACC			UL(0)

/* WRAPCFG Register */
#define XSPI_WRAPCFG_DSSFTCS0		U(8)

/* LIOCTL Register */
#define XSPI_LIOCTL_RSTCS0			U(16)
#define XSPI_LIOCTL_RSTCS0_MSK		(0x1U << XSPI_LIOCTL_RSTCS0)

#endif /* _XSPI_REG_H_ */
