/*
 * Copyright (c) 2023, Renesas Electronics Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef PLAT_TZC_DEF_H
#define PLAT_TZC_DEF_H

/* Platform specific TrsutZone setup constants */

#define PLAT_TZC_REGION_ACCESS_ID_MASK	U(0x3)

#define PLAT_TZC_REGION_ACCESS_RDWR(nsaid)	\
	(TZC_REGION_ACCESS_RDWR(nsaid & PLAT_TZC_REGION_ACCESS_ID_MASK))

#define PLAT_TZC_REGION_ACCESS_S_PRIV		\
	(PLAT_TZC_REGION_ACCESS_RDWR(0x1))

#define PLAT_TZC_REGION_ACCESS_S_UNPRIV		\
	(PLAT_TZC_REGION_ACCESS_RDWR(0x0) | PLAT_TZC_REGION_ACCESS_S_PRIV)

#define PLAT_TZC_REGION_ACCESS_NS_PRIV		\
	(PLAT_TZC_REGION_ACCESS_RDWR(0x3) | PLAT_TZC_REGION_ACCESS_S_UNPRIV)

#define PLAT_TZC_REGION_ACCESS_NS_UNPRIV	\
	(PLAT_TZC_REGION_ACCESS_RDWR(0x2) | PLAT_TZC_REGION_ACCESS_NS_PRIV)


/* Trusted Firmware(BL31) secure DRAM */
#define PLAT_FW_TZC_PROT_DRAM01_BASE	(0xC0000000)
#define PLAT_FW_TZC_PROT_DRAM01_SIZE	(0x00040000)
#define PLAT_FW_TZC_PROT_DRAM01_END		\
	(PLAT_FW_TZC_PROT_DRAM01_BASE + PLAT_FW_TZC_PROT_DRAM01_SIZE - 1)

/* OP-TEE secure DRAM */
#define PLAT_TEE_TZC_PROT_DRAM01_BASE	(0xC0100000)
#define PLAT_TEE_TZC_PROT_DRAM01_SIZE	(0x00020000)
#define PLAT_TEE_TZC_PROT_DRAM01_END		\
	(PLAT_TEE_TZC_PROT_DRAM01_BASE + PLAT_TEE_TZC_PROT_DRAM01_SIZE - 1)

void plat_security_setup(void);

#endif /* PLAT_TZC_DEF_H */
