include:
  - local: gitlab-ci/yaml-files/templates/mpu-build-templates-gitlab-ci.yml

rzg3s-release-no-configs:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "release"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-release-vbat:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "release"
    CONFIGS: "PLAT_SYSTEM_SUSPEND=vbat"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-release-awo:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "release"
    CONFIGS: "PLAT_SYSTEM_SUSPEND=awo"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-release-vbat-m33:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "release"
    CONFIGS: "PLAT_SYSTEM_SUSPEND=vbat PLAT_M33_BOOT_SUPPORT=1"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-release-awo-m33:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "release"
    CONFIGS: "PLAT_SYSTEM_SUSPEND=awo PLAT_M33_BOOT_SUPPORT=1"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-release-awo-disable-m33:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "release"
    CONFIGS: "PLAT_SYSTEM_SUSPEND=awo PLAT_M33_BOOT_SUPPORT=0"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-release-stack-protector-0:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "release"
    CONFIGS: "ENABLE_STACK_PROTECTOR=0"
  extends:
    - .overnight_mpu_build_fail_job_template

rzg3s-debug-log0:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=0"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-debug-log50:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-debug-log50-vbat:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLAT_SYSTEM_SUSPEND=vbat"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-debug-log50-awo:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLAT_SYSTEM_SUSPEND=awo"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-debug-log50-vbat-m33:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLAT_SYSTEM_SUSPEND=vbat PLAT_M33_BOOT_SUPPORT=1"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-debug-log50-awo-m33:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLAT_SYSTEM_SUSPEND=awo PLAT_M33_BOOT_SUPPORT=1"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-debug-log50-awo-disable-m33:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 PLAT_SYSTEM_SUSPEND=awo PLAT_M33_BOOT_SUPPORT=0"
  extends:
    - .overnight_mpu_build_job_template

rzg3s-debug-log50-stack-protector-0:
  variables:
    PLAT: "g3s"
    BOARD: "smarc"
    BUILD_TYPE: "debug"
    CONFIGS: "DEBUG=1 LOG_LEVEL=50 ENABLE_STACK_PROTECTOR=0"
  extends:
    - .overnight_mpu_build_fail_job_template