/*
 * Copyright (c) 2022, Renesas Electronics Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef PLAT_TZC_DEF_H
#define PLAT_TZC_DEF_H

#include <rz_soc_def.h>

/* Platform specific TrsutZone setup constants */

#define PLAT_TZC400_DDR_FILTER_NUM		U(0x3)

#define PLAT_TZC_REGION_ACCESS_ID_MASK	U(0x3)

#define PLAT_TZC_REGION_ACCESS_RDWR(nsaid)	\
	(TZC_REGION_ACCESS_RDWR(nsaid & PLAT_TZC_REGION_ACCESS_ID_MASK))

#define PLAT_TZC_REGION_ACCESS_S_PRIV		\
	(PLAT_TZC_REGION_ACCESS_RDWR(0x1))

#define PLAT_TZC_REGION_ACCESS_S_UNPRIV		\
	(PLAT_TZC_REGION_ACCESS_RDWR(0x0) | PLAT_TZC_REGION_ACCESS_S_PRIV)

#define PLAT_TZC_REGION_ACCESS_NS_PRIV		\
	(PLAT_TZC_REGION_ACCESS_RDWR(0x3) | PLAT_TZC_REGION_ACCESS_S_UNPRIV)

#define PLAT_TZC_REGION_ACCESS_NS_UNPRIV	\
	(PLAT_TZC_REGION_ACCESS_RDWR(0x2) | PLAT_TZC_REGION_ACCESS_NS_PRIV)

/* Trusted Firmware(BL31) secure DRAM 0x43F00000 - 0x440FFFFF */
#define PLAT_FW_TZC_PROT_DRAM01_BASE	(0x43F00000)
#define PLAT_FW_TZC_PROT_DRAM01_SIZE	(0x00200000)
#define PLAT_FW_TZC_PROT_DRAM01_END		\
	(PLAT_FW_TZC_PROT_DRAM01_BASE + PLAT_FW_TZC_PROT_DRAM01_SIZE - 1)

/* OP-TEE secure DRAM 0x44100000 - 0x47DFFFFF */
#define PLAT_TEE_TZC_PROT_DRAM01_BASE	(0x44100000)
#define PLAT_TEE_TZC_PROT_DRAM01_SIZE	(0x03D00000)
#define PLAT_TEE_TZC_PROT_DRAM01_END		\
	(PLAT_TEE_TZC_PROT_DRAM01_BASE + PLAT_TEE_TZC_PROT_DRAM01_SIZE - 1)

void plat_security_setup(void);

#endif /* PLAT_TZC_DEF_H */
